XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
  XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXXXXXXXXXXXXX XXXXXX XXXX XXXXXXXXXXXXX

    XXXX XXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXX XXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXXXX XXXXXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXXX
      XX XXXXXXX XXXXXX XXXXX XXXXXXX XX XXXXXX XX XXXXX XXXXXXXXXXXX XXX XXX XX XXXX
      X
        XXXXXXX
        XXXXXXXX
        XXXXXXXXXX
        XXXXXXXXXXX
        XXXXXXXXX
        XXXXXXXXX
        XXXXXXXX
        XXXXXXXXXXX
        XXXXXXXXXXXX
        XXXXXXXXXX
        XXXXXXXXXXXX
        XXXXXXXXXXXX
        XXXXXXXXXXX
        XXXXXXXXXXXXX
        XXXXXXXXXXXXX
        XXXXXXXXX
        XXXXXXXXX
        XXXXXXXXX
        XXXXXXXXXX
        XXXXXXXXXXX
        XXXXXXXX
        XXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXX X XXXXXXXXXX X
          XXXXX XXX XXXXXXXXXXXX XXX XXX X XXXXXXXXXX X XXXX XXXXXX XX XXX XXXXXXXX XX XXXX XXXXXXXXX XXX XX XXXXXXXXXX XXXX XXXXXX XXXXXX XXXXXX XXXXX XXXXXXX XXX XXXXXX XXXXXXXX XXXXXX XXXX XXXXXXX XXXX XXXXXXX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X
      XX

      XX XXXXXXX XXXXXXXXXXXXX XX XXXX XXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXX X XXXX

      XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXX XXX X XX
      XXX XXXXXXXX

      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXX XXXXX X XX
        XXX XXXX X X XX X X XXXXXXXXXXX XXXX X
          XXX XXXXXXX X XXXXXX
          XXXXXXXXXXXX
            XXXXX XXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXX
            XXXXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXXX
            XXXXXXX XXXXXXXXXXXXXX
          XX
        X
        XXXXXXXXXXXXXXXXX X XXXXX

        XXXXXXXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXX
      XX

      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXX X
          XX XXXXXXXXXXXXXXXXX X
            XXXXXXXXXXXX X XXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXX
          X
        XX
      XX

      XX XXXXXXX XXXXXXX XXXXXXXXX XX XXX XX XXXXX XXXXX XXXXXXXXX
      XX XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXXXXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXX XXXX XX XXXXX X XX
        XX

        XXXXXXXXXXXXXXXXXXXXX X
          XXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXX XXXXX XX XX
        XX
      X
    XXXXXXXXX

    XXXX XXXXXXXXXX XXXXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXX XXXX XXXXX XXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXX
  XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXX
  XXXXXXX
XXXXXXX
