XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
  XXXXXX
    BBBBBBB BBBBBBBBBBB
  XXXXXXX
  XXXXXX
    BBBBBBB BBBBBBBBBBB

    BBBBBBB BBBBBBBBBBBBBBBB

    BB BBBBBBBBBBB BB BBBBBBBB
      
    BBBB
      XXXXX XXXXXXXXXXXX XXXXXXXXXXXX
        
      XXXXXXX
    BBBBB

    BBBBBBB BBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBB
  XXXXXXX
XXXXXXX
