XXXXXXXXX XXXXX
XXXXX XXXXXXXXXX
  XXXXXX
    BBBBBBB BBBBBBBBBBB
  XXXXXXX
  XXXXXX
    BBBBBBB BBBBBBBBBBB

    BBBBBBB BBBBBBBBBBBBBBBB

    XXXX XXXXXXXXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXX XXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXXXXXXX
          BBBBBBB BBBBBBBBBBBBBBBBB
        XXXXXX

        BB BBBBBBBB
          XXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXX
             FFFFFFFF
          XXXXXX
        BBBBB

        XXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXX XXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXX
          XXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXX FFFFFFFFXXXXX
          XX XXXXXXXXXXXXXXXX FFFFFFFFXXXX
          BBBBBBB BBBBBBBB
          
        XXXXXXX
      XXXXXX
    XXXXXX

    BBBBBBB BBBBBBBBBBBB
  XXXXXXX
XXXXXXX
