XXXXXXXXX XXXXX
XXXXX XXXXXXXXXBB BBBBBBBBBBBBBBB XXXXXXXXBBBBBX
  XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXX
    XXXXXXX FFFFFFFF X  FFFFFFFFXXXXXXXX

    XXXXX XXXXXXXXXXXXXXX XXXXXX FFFFFFF FFFFFFFFXX

    BBBBBBB BBBBBBBBBBBBBBB

    XXXXXXX
      XXXXXXXXXXXXXXXXXXX X
        XXXXXXXXXX XXXXXXXXX
        XXXXXXXXXXXX XXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXXXXXX XXXXX
        XXXXXXXXXXXX XXXXX
      X

      XXXXXX XXXXXXXXXXX XXXXXX X
        XXXXXXXXXXXXXXXXXXXXXX X
          XXXXXXXXXX XXXXXXX
        X
      X
    XXXXXXXX

    B BBB BBB BB BBBBBBBBBBBBBB
    XXXX XXXXXX XXXXXX XXX XXXX XXXXXXXX XXX
    XXXXX XXXXXXX XXXXXXXXXXXXXXXXX
    B BBBBBB
  XXXXXXX
  XXXXXBB BBBBBBBBBBBBBBB XXXXXXXXBBBBBX
    

    B BB BBBBBBBBBBBBBBB BB BBBBB B
      XXXXXXX XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

      B BB BBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBB B
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      B BBBB B
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      B BBBBB B

      B BBB BB BB BBBBBBBBBBBBB
        XXXXXXX XXXXXXXXXXXXXXXX
      B BBBBBB
    B BBBBB B
  XXXXXXX
XXXXXXX
