XXX
XXXXXXX XXXXXXX
XXX

XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXX
  XXXX XXXXXXXXXXXXXX XXXXXXXXX
    XXX XXXXXXXXXXXXXXX XXXXXX FFFFFFFFXXXXX
    XX XXXXXXXXXXXXXXXX FFFFFFFFXXXX
    B BB BBBBBBBBBB BB BBBBBBBBBB B
    XX XXXXXXX XXXXXXXXXX XXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXXXXX
    B BBBBB B
  XXXXXX
  BBBBBBB BBBBBBBB
XXXXXXXXX

XXXXX XXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXX
  
XXXXXXX
