XXX
XXXXXXX XXXXXX
XXXXXX XXXXXXXX
XXXXXXXXXXXX XX XXXXXXXX XX XXXXXX XXXXXXXXXXXXX XXX XXXXXX XXXXX XXXXXXX XX XXXXXXXXXX XXXX XX XXXXXXX XXX
XXX

XXXX XXXXXXXXXXXX
BBB BBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
  XXXX XXXXXXXXXXXXXXX
    XXXXXXXXX
    XXXXXXX
    BBBBBB BBBBBBBB B BBBBBBBBBBBBBBBB B BBBBBBB
    BBB BBBBBBB BB BBBBBBBB
      BB BBBBBBBBBBBBBXXXX XXXXXXXXXXXXXXXXXXXBBBBB
      BB BBBBBBBBB BB BBBBBBBBBBBBBBBBB
        XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXX
          
          XXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX
      BBBB
        XX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXXX XXXXXXXXXX
          
        XXXX
      BBBBB
      BB BBBBBBBBBBBBXXXXXXBBBBB
    BBBBBB
  XXXXXX
BBBBBB
XXXXXX
