XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXXX XXXXXXXXXX
XXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
XXXX X XXXXXXX XX XXXXXXXX X X
XXX X XXXXXXX X X
XXXXXXXX
XXXXXXX
XXXXXXXX
XX XXXX XXXX XXXXXXXX XXXX XXXX XXXXXX XXXXX X XXXXX XXXXX XX XXX
XX XXXXX XXXX XX XXX XXXX
XXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX

XX XXXX XXX XX XXX XXXXXX XX XXXX XX XXX XXXXXX XXX XXXXXX XXXX XXXX
XX XXXXXXXXXX XXXX XX XXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXXXXXXX X
  XX XXXXXXX XXX XXXXXXX X
    XXX X
      XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    X XXXXX XXXX X
      XX XXX XXXXXX XXXX XXXX XXXX XX XXXXXX XX XXX XXX XXXX
    X
  X
X

XX XXXX XXX XXXXXXXXX XXX
XXXXXXXXX XX X
  XXXXXXXXXXXXXX X XXXXXX X X XXXXXXXXXX
  XX XXXX XXX XXXXXXXXXX XXXX XXXXX XXXXXXXX
  XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXX X XXXXXXXXXXXXX
  XXXXXXXXX X XXXXXXXXXXX
  XXXXXXXXX X XXXXXXXXX XXX XXXXXXXXX
      X XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXX X XXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX
XXXXXXXXX

XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXX XXXXX XXXXXXXX XXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXX
XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
XX XXX XXXXX XXXXX XXXXX XXX XXXX XXXXXX XXXXXXXXXXX
XX XXX XXXXXXXXXXXXXX XX XXXXX XXXXXXXXXX
XXXXXXXX XXXXXXXXXXXXXXXXX X
  XXX XXXX X X XXX XXX XXXXX XXX X
    XXXXXXXXXXXX X X XXXXXXXXXXXXXXX
  X
X
XXXXXXXXXXXXXXX
XXXXXXXXXXXXX
X X XXXXXX XXXX X
X X XXXXXX XXXX X
X X XXXXXX XXXXXXX X
XXXXXXXXXXXXXX
XXXXXX
XXXXXX
XXXXXXXXXXXXXX
