B BBBBBBB B
  XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
  XXXXX XXXXXXX XX X XXXXXX XXXX XXXXXXXX X XXX XXXXXXXXX XXXX XXX XXX
  XXXX XXXXXXXXXXXXXXX
B BBBBBBBBBB B

B BBBBBB BBBBB B BBBBBBBBBBBBBBB B BBBBBB B B B

B BBB BBBB BB BBBBB B
  BB BBBB BBBBBBBB BBB
    BB BBBB BBBBBBBB BBBBBBBBB BBBBBBBBB B BBBBBBBBBBBBBB BBBBBBBBB B BBBBBBBBBB
    B BBBBBB BBBB B BBBB B BBBBBB BBB B
    B BBBBBB BBBBBBB B BBBBBBB B BBBBBBBBBBBBBB B
    B BBBBBB BBBBBB  B BBBBBBB B BBBBBBBBBBBBBB B BBBBBBB BBB B

    B BBBB BBBBBBB B
    B BBBB BBBBBBBBBBB B
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    B BBBB BBBBBB B
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXX
    B BBBB BBBBBBBBBBBBBBB B
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX XXXX XXXXX
    B BBBB BBBBBBBBBBB B
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXX
    B BBBB BBBBBBBBB B
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXX
    B BBBB BBBBBBBBBB B
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX XXXXX
    B BBBB BBBBBBBB B
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXX
    B BBBB BBBBBBBB B
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXX XXXXX XXXXX
    B BBBB BBBBBBBBBBB B
      XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX
    B BBBB B
      XXXXXXXXXXXXX XXXXXXXXXXXXXX
    B BBBBBBB BBB BBBBBBBBBX BBBBB

  BBBB
    
  B BBBBB B
B BBBBBB B
