B BBBBBBB B
  XXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXX
  XXXXX XXXXXXX XX X XXXXXXX XXXX XXX XXXXXXX
  XXX XXXX XX XXX XXX XXXX XXXXXXXXXX XXXXXXX XXXXXXX
B BBBBBBBBBB B
B BBBBBB BBBBBBBBB B BBBBBBBBBBBB B BBBBBBBB BBBBBB B
XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
   FFFFFFFFFFF F
XXXXXX
