XXXXX XXXXXXXXXXXXXXXX XXXXXX XXXXXXXXXXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
  XXXXXXX XXXXXXXXXX XXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXX XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXXXXXXX
    B BBBBBBB BBBBBBBBBBBBBB BBBBBBBBBB BBBBBBBBBBB B
  XXXXXXXXX
XXXXXXX

XXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXX
  B BBBBBB BBBBBBBBB B BBBBBBBB B BBBBBB BBB B BBBB B
  B BBB BBBBB BB BBBBBBBBBBBBB B
  B BBBBBB BBBB B BBBBBBBBBBB B BBBBB B
  B BBBBBB BBBBBBBBB B BBBBBBBBBB B BBBBBBB B
  B BBBBBB BBBBBBBBBB B BBBBBBBBBBB B BBBBBBB B
  B BBBBBB BBBBBB B BBB B

  B BB BBBBBBBBBB BB BBBBBBBBBB B
    B BBBBBB BBBBBB B BBBBBBBB B
  B BBBBB B

  XXXX XXXXXXXXXXXXXXXXXXBBBBBB BBBBBB BB BBB BBBBBBBBBXX
      XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXBB BBBBBBBBBXBBBBBXX
        
      XXXX

      XXX XXXXXXXXXX XXXXXXXXXXXX
        B BBB BBB BB BBBBBBBBBBB B
          B BBBBBB BBBBBBBB B BBBBBBBBB B BBBBBBB B
          B BBBBBB BBBBBB B BBB B

          B BB BBBBBBBBBB BB BBBBBBBBBB BBB BBBBBBBBB BB BBBBBBBB B
            B BBBBBB BBBBBB B BBBBBBB BBBBBBBBBBBBBBBBBB B
          B BBBBB B

          XXXBBBBBB BBBBBB BB BBB XXXXXXXXBBBBBBBBBX
            XX XXXXXXXXXXXXXXXXX
              
            XXXX
          XXXXX
        B BBBBBB B
      XXXXX
    XXXXXX
  B BBBBBB B
XXXXXX
