B BBBBBBB B
  XXXXXX XXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXX
  XXXXX XXXXXXX XX X XXXXXXX XXXX XXX XXXX XXXXXXX

  XXXX XXX XX XXX XX XXX XXXXXXXXXX
    XX X XXXX XXXXXXXXX
    XXXXX X XXXXXXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXXXXXXX X XXXXXXXX XXXXXXXXX
    XXXXXXXXX XXXXXXXXXXX X XXXXXXXX XXXXXXXXX
B BBBBBBBBBB B

B BBBBBB BB B BBBBBBBBBB B
B BBBBBB BBBBB B BBBBBBBBBBBBB B

B BB BBBBBBBBBBBBBBBBBBBB BB BBBB B
XXXXBB BB XXXXXBBBBB XXXXXXXXXXXXXXXXXBB BBBBB BBBBBXX
  
XXXXXX
B BBBBB B

B BB BBBBBBBBBBBBBBBBBBB BB BBBB B
  B BBBBBBBBB BBBB B
    B BB BBBBBBBBBBBBBBB BBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB B
      XXX XXXXXX XXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXX
        X XXXXXXXX XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX
        X XXXXXXXX XXXXXXXXX XXXXXXXXXX
        X XXXXXX XXXX XXX

      B BB BBBBBBBBBBBBBBB BBBBBBBB BBBBBBBBBBBBBBBBBBB B B
        XXX XXXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXX
          X XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX XXX
          X XXXXXXXX XX XXXXXXXXX XXXX XXXXXXXX
          X XXXXXX XXXX XXX
        B BBBBBB BBBBBBBBBBB B BBBBBBBBBBBBBB B BBBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB BB B BBBBB B
      B BBBBB B

      B BBB BBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB B
        B BB BBBBBBBBBBBBB BBBBBBBB BBBBB BBBBBBBBBBBBBBBBBBBBBBBBBB B
          B BBBBBBB BBBBBBBBBBBBBBB B
            XXXX XXXXXXXXX BB BBBBBBBBBBBXXXXXXXX BBBBBXXXXXXXXXX
          B BBBBBBBBBB B
          
        B BBBB B
          
        B BBBBB B
      B BBBBBB B
    B BBBB B
      
    B BBBBB B
  B BBBBBBBBBBBB B
B BBBBB B
