XXXXX XXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXX FFFFFFFF FFFFFFFFFFFFFFFF  FFFFFFFFXX
XXXXX XXXXXXXXXXXXX XXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXX

XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXX

XXXXXXX
  B BB BBBBBBBBBB B
     FFFFFFFF X  FFFFFFFF
  B BBBB B
     FFFFFFFF X  FFFFFFFF
  B BBBBB B
XXXXXXXX

XXXXX XXXXXXXXXXXXXXX XXXXXX FFFFFFF FFFFFFFFXX

BBBBBBB BBBBBBBBBBBBBBB
BBBBBBB BBBBBBBBBBBBB
BBBBBBB BBBBBBBBBBB
BBBBBBB BBBBBBBBBBBBBB
