XXXXXXXXX XXXXX
XXXXX XXXXXXXXXXXXX
XXXXXX
    XXXXXXXXXXXXXX XXX XXXXXX XXXXXXXXXXXXXXXX
XXXXXXX
XXXXXX
XXXXXXXX
    XXXX XXXXXXXX
    XXXXXXXX XXX XX X
        XXX XXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXXX X XXXXXXXXXXXXX
        XXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXX
        XXX XXXXXXXX XXX XXXX

        XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
            XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X XXXX X
            XX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        X

        XXX X XXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXX XXXXXXXXXX X XXXXXXX X XXX X XXXXXXXXXXXXXX XXXXXX X XXXXXXX
        XX X XX X XXXXXXXXXXXXXX X XXXXXXXXXX X XXXX
                XXXXXXXX XXXXX XXXXXX X
                    XXXXXX XXX XXX XX X XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXX
                X
        X X XXX

        XXXXXXX X XXXXXXXX XXX XXXXXXXXXX

        XX XX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXX XX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXX XX
          XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXXXXXXX
        X XX XXXXXXXXXXXXXXXXXX X
            XX XXXXXXXXXX X
                XXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXX
                    XXXXXX XXXXXXXXXX
                    XXXXXXXX XXXXXXXXXXXXXX XXX XX XXXXXXX XXXXXX XXXXX XXX XXXXXXX XX XXXXXX XXXXXX XXXXX XXXXXX XXXXXXXX XXXX XXXX XXXXXXX
                XXX
            X

            XX XXXXXXXXX X
                XXXXXX XXXXXXXXXXXXX
                XXXXXXXXXXXXXXXX X XXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
            X XXXX X
                XXX XXXXXXXXXXXXXX
                XX XXXXXXXXXX X
                    XXXXXXXXXXXXX X XXXXXXXXXXXXXXXX X X
                        XXXXXXXXXXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXX XX X X XXX XXXXXXXXXX XXXXXXXX XXXX XXX XXXXXXX XX X
                        XXXXXXXXXXXXX X XXXXX XXXXX XXXXXXXXXXXXXX X XXXX
                X

                XXXXXXXXXXXXXX
                    XXXXXXX XXXXXXXXXXXXXXXXX
                    XXXXXXX XXXXXXX
                    XXXXXX XXXXXXXX
                    XXXXXXXX XXXXXXXXXXXXX XX XXXXXXXXXXXXXXX XXXXXXXX XX XXXXXXXXXX XXXXXXXX XXXX XXX XXXXXXX
                XXX
            X
        X XXXX X
            XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXX XXX XXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXX
        X
        XXXXXXXXXXXXXXX
    X

    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX XX X
      XXXXXX
    XXX
XXXXXXXXX
XXXXXXX
XXXXXXX
