XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXX

        XXXX XXXXXXXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX
            XXXX XXXXXXXX XXXXXX XXX
            XXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXX XXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXX

            XXXX XXXX XXXXX XXX
            XX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
        XXXXXX

        XXXX XXXXXXXX XXXXXXXXXX XXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX
            XXXX XXXX XXXXXXXXXX XXX
            XXX XXXXXXXXXX XXXXXXXXXXXX
            BBB BBBBBBBB BB BBB
            BB BBBBBBBBBBBBBBBBB
                XXX XXXXXXXXXXXXXXXBB BBBBBBBBBBBBBBB XXXXXXBBBBBXX
                    XX XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XX XXXXXXXXXXXXXXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXXXXXXX
                    BBB BBBBBBBB BB BBBBBBBBBBBBBBBBB
                        XXX BB BBBBBBBBBBBBBBBXXXXXXXXXXXXXXBBBBBX
                            XX XXXXXXXXXXXX
                        XXXXX
                    BBBBBB
                    XXXXX
                XXXXX
            BBBB
                XXX BB BBBBBBBBBBBBBBBXXXXXXXXXXXXXXBBBBBX
                    XX XXXXXXXXXXXX
                XXXXX
            BBBBB
            BBBBBB
            XXXXX

            XXXX XXXXXXX XXXXXXXXXX XXX XXXX XXXXX XXX
            XXX XXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXX
                BB BBBBBBBBBBBBBB
                XXXX
                    XX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX
                XXXXX
                BBBBB
				BB BBBBB
                XXX BB BBB BBBBBBBBBBBBBXXXXXXXXXXXXXXXXBBBBBX
                    XX XXXXXXXXXX BB BBBBBBBBBBBBBXXXXXXXBBBBBX
                        XX XXXXXXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX
                    XXXX
                XXXXX
                XXX BB BBB BBBBBBBBBXXXXXXXXXXXXXXXXBBBBBX
                    XX XXXXXXXXXX BB BBBBBBBBBXXXXXXXBBBBBX
                        XXXX XX XXXXXXXXX XXXXXXXXXXXXXXXXXXXX
                    XXXX
                XXXXX
				BBBBB
                BB BBBBBBBB
                XXXX
                    XX XXXXXXXX
                        BB BBBBBBBBB BB BBBBBBBB
                            XX XXXXXXXXX XXXXXXXXXXXXXXX
                        BBBB BBBBBBBBB BB BBBBBBBBBBB
                            XX XXXXXXXXX XXXXXXXXXXXXXXXXXX
                        BBBBB
                        
                    XXXX
                XXXXX
                BBBBB
            XXXXX
        XXXXXX
    XXXXXX
XXXXXX
