XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
  XXXXXX
    XXXXXXXXXXXXX X XXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX

    XXXXXXX
      XXXXX XXXX X
        XXXXXXXX XX
        XXXXXXX XX
        XXXXXX XXXXX
        XXXXXXX XXXXX
      X
      XXXXX X
        XXXXXX XXXXX
        XXXXXXX XXXXX
        XXXXXXXXXXXXXXXXX XXXX
      X
    XXXXXXXX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXX
          XXXXXXXXXXX XXXXX
          XXXXXXXXXXXX XXXXX
          XXXXXXXXX XXXXXXXX XXXXXXXXX XXXXXX XXXXXXX X
            XXXXXXXXXXXXXXXX XXXXX X X  XXXXX X XXX X  XXXXXXXX
          X
        XXX
      XXX
    XXXXXXXXX
  XXXXXXX

  XXXXXX
    XXXX XXXXXXXXXXXXXXXX
  XXXXXXX
XXXXXXX
