XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
XXXXXXXXX XXXX XXXXXX XXXXXXXXXXXX XXXXX XXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX
  XXXXXX
    XXXXXXXXXXXXX X XXXXXX XXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX

    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXX X
        XXXXXX XXXXXXXXXXXXXX XX XXXXXX XX XXXXXXXXXXXXXXXXXXX XX XXXXXX XX XXXXXXXXXXXXXXXXXXXXXXXXXX X XX
      X

      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
        XXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXX XXXXXXXXXXXX
          XXXXXXXXXXX XXXXXX
          XXXXXXXXXXXX XXXXXX
          XXXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXX XXXXXXX X
            XX XXXXXXXXXXXXXXXXX X
              XX XXXXX XXX XX X XXXXXX XXXXXXX XXXXXX XXX XXXXX
              XXX XXXXXXX X XXXX XXXXXXX XX X XXXXXX X XX XXXXX XXX XXX XXXXX X X XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXX
            X
          XX
          XXXXXXXXXXXXX XXXXXXXX XXXXXXXXX XXXXX XXXXXXX X
            XX XXXXXXXXXXXXXXXX X
              XXX XXXXX XXX XX X XXXXXX XXXXXXX XXXXXX XXX XXXXX
              XXX XXXXXXX X XXXX XXXXXXX XX X XXXXXX X XX XXXXX XXX XXX XXXXX X X XXXXXXXXXXXXXXXXXXX
              XXXXXXXXXXXXXXX
            X
          X
        XXX
      XXX
    XXXXXXXXX
  XXXXXXX

  XXXXXX
    XXXX XXXXXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXX XXXXXXXXXXXXXX
  XXXXXXX
XXXXXXX
