XXXXXX
    XXXXXX
        XXXXX XXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX
    XXXXXXX
    XXXXXX
        XXXXXXX
            XXXXX XXXXX XXXXX X
                XXXXXX XXXXX
                XXXXXXX XXXXX
                XXXXXXX XX
            X
        XXXXXXXX
        XXXX XXXXXXXXXXXXXXXX
        XXXXXXXX

            XXXXXXXXX
                XXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXX XXXXXXXXX X

                XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXX XXXXX X XXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXX XXXXX
                        XXXXX XXXXX XXXXXXXXXXXXXXXXX
                        XXXXXX XXXXX XXXXX XXXXX XXXXX XXXXX
                        XXXXX XXXXX XXXXX XXXXX XXXXXX XXXXXXX
                XXX XXXX X XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
                        XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX

                XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXX X XXXXXXXXXXXXXXXXX XXXXXX X
                    XXXXXX XXXXXXXXX XXXXXXXX XXXXXXX XX XXXXX
                XXX

                XXXXXXXXXXXXXXXXX
                    XXXXXXXX X
                        XXXXXXXXX XXXXX
                    XX
                    XXXXXXXXXX XXXXXX
                    XXXXX X
                        XXXXXXX XXX
                    XX
                    XXXXXX X
                        XXXXX XXXXXXXXXXX
                        XXXXX XXXXX
                    XX
                    XXXXXX X
                        XXXXX XXXXXXXXXXX
                        XXXXX XXXX
                    XX
                    XXXXXXXXXX X
                        XXXX XX
                        XXXX XXX
                        XXXXXXXXXXX XXXX
                    XX
                    XXXXXXX XX
                        XXXXX XXXXXX XXXXXX
                        XXXXX XXXXXXXXXX
                        XXXXX XXXXX
                        XXXXXX X
                            XXXXXXX X
                                XXXXX XXXX
                            X
                        XX
                        XXXXXXXXXX X
                            XXXXXXXXX X
                                XXXXXXXXXXX XXX
                                XXXXXXXXXXXX XXXXXXXX XX XX XXXXX
                            X
                        X
                    XX
                XXX
            XXX

        XXXXXXXXX
    XXXXXXX
XXXXXXX