XXXXXX
    XXXXXX
        XXXXX XXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XX
    XXXXXXX
    XXXXXX
        XXXXXXX
            XXXXX XXXXX XXXXX X
                XXXXXX XXXXX
                XXXXXXX XXXXX
                XXXXXXX XX
            X
        XXXXXXXX
        XXXX XXXXXXXXXXXXXXXX
        XXXXXXXX

            XXXXXXXXX
                XXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXX XXXXXXXXX X

                XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXX X
                    XXXXXXXXX XXXXXXXX
                XXX

                XXX XXXXX X XXXXXXX XXXXX XXXXX XXXXX XXXXX XXXXX XXXXX
                        XXXXX XXXXX XXXXXXXXXXXXXXXXX
                        XXXXXX XXXXX XXXXX XXXXX XXXXX XXXXX
                        XXXXX XXXXX XXXXX XXXXX XXXXXX XXXXXXX
                XXX XXXX X XXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX
                        XXXXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXX

                XXX XXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

                XXXXXXXXXXXXXXXXX
                    XXXXXXX X
                        XXXXX XXXXXXX XXXXXX
                    XX
                    XXXXXX XXX
                    XXXXXXXX X
                    XX
                    XXXXXXXXXX XXXXXX
                    XXXXXXXXXX X
                        XXXXX XXXXXXXXXXX
                        XXXXX XXXXXX
                        XXXXXXXXXXXX XXXXXX
                        XXXXXXXXXX X
                            XXXXX XXXXX
                            XXXXXXXXXX X
                                XXXXXX XXXXXXX
                                XXXXX XXXXXXXX
                            X
                        XX
                        XXXXXXXXX X
                            XXXXX XXXXX
                        X
                    XX
                    XXXXXXXXXXX X
                        XXXXX XXXXXXXXXXX
                        XXXXX XXXXX
                        XXXXXXXXX X
                            XXXXX XXXXX
                        XX
                        XXXXXXXXXX X
                            XXXXXXX XX
                        X
                    XX
                    XXXXXXX XX
                        XXXXX XXXXXX XXXXXX
                        XXXXX XXXXXXXXXX
                        XXXXXXXXXXXXXXXXX XXXXXXXX
                        XXXXXXXXXX X
                            XXXXXXX X
                                XXXXXX XXXXXXXXX
                            X
                        XX
                        XXXXXXXXXXX XXXXXXXX XXXXX X
                            XXXXXX XXXXXX X XX
                        XX
                        XXXXX XXXX
                    XX
                XXX
            XX

        XXXXXXXXX
    XXXXXXX
XXXXXXX