XXXXXX
    XXXXXX
        XXXXX XXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX
    XXXXXX
        XXXXXXX
            XXXXX XXXXX XXXXX X
                XXXXXX XXXXX
                XXXXXXX XXXXX
            X
        XXXXXXXX
        XXXX XXXXXXXXXXXXXXXX
        XXXXXXXX


            XXXXXXXXX
                XXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXX
            XX XXXXXXXX XXXXXXXXX X

                XXX XXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

XXXXXX X X
    XXXXX X X
        XXXXX XXXXXX
        XXXXXXXX XXXXXXX
        XXXXXXXXXX
    XX
    XXXXXXX X X
        XXXXXXXX XXXXXX
    XX
    XXXXXXX X
        XXXXXXX XXXXXXXXXXX
        XXXXXXXXX
        XXXXXXXXXXXX
    XX
    XXXXXXXXXX X
        XX XXXXXXXXXXXXX XXXXXXXXX
        XXXXXXX X
            XXXXX XXXXXX
            XXXXX XXXX XXXX XXXXXX
            XXXXX XXXX XXXX XXXXXX
            XXXXX XXXX XXXX XXXXX
            XXXXX XXX XXXX XXXX XXXXXX XXX X XXXXXXXXXXXXXXXX
            XXXXXXX XXXX XXXXXX XXXXXXXXXXXXXXX XXXXXX XXXXXXXX
            XXXXX XX XXXX XX XXXXXX XXXXXXXXXXXXX XXXXXX XXXXXXXXX
            XXXXX XX
        XX
        XXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXX
    XX
    XXXXXXXX X
        XXXXX XXXXX
        XXXXXX X XXXXXXXXXXX
        XX XXXXXXXX
        XX XXXXXXXXX
        XXXXXXX X X
            XXXX X XXXXXX XXXXXX
            XXXXXXXX X XXXXXX XXXXX XXXXXXXXX XXXXXXX
            XXXXXXX X XXXXXX XXXXXX
            XXXXXXXXXXX X XXXXXX XXXXX
        X
    XX
    XXXXXXXXXXXXXXX X
        XXXXX XXXXX
        XX XXXXXXXX
        XXXXXXXXXXXXXXX X
            XXXXXXXX XXXX
        X
    XX
    XXXXXX X X
        X
            XXXXX XXXXXX
            XXXXX XXXXXX
            XXXXXXXX XXXXXXXX
            XXXXX XXXXXX
            XXXXXXXXXXX
                XXXXXXXX
                    XXXXXXX
                        XXXXXXXXXX
                        XXXXXXXXXX X
                           XXXXXX XXXXXXXXX XXXX XXXXX
                        X
                    X
                XX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX
            XXXXXX
                XXXXXX XXXXXXXXXXX XXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXX
                XXXXXX XXXXXXXXXXX XXXXX
                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        X
    X
XX

                XXXXXXXXXXXXXXXXXXXXXXXX
            XX

        XXXXXXXXX
    XXXXXXX
XXXXXXX