XXX
XXXXXX XXXX X XXXX XXXX XX XXXX XXXXX
XXXXXXX XXXXXXX
XXXXXXXX XXXXXXX
XXX

XXXXXX X XXXXX XXX XXXXXX XX XXX XXXX XXXXX

XXXXXXXX XXXXXXXXXXXXXXX
XXXX XXXXXXXXXXXXXXXXXXXXXXX

XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXX XX X

  XXXXXXXX XXXXXXXXXXXXXX XXXX X
    XXXXXXXXXXXXX X XXX XXXXXXXXXXXX XXXXXXXXXXXXXXX X XXX X XXXXXXX
  X

  XXXXXXXX XXXXXXXXXXXXXXXX XXXXX XXXXXXXX X
    XXXXXXXXXXXXX X XXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX X XXX X X X XXXX X XXXXXXXX X
      XXXXXXXX X X X XXXXXXX X XXXXXXX
  X

  XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XX XXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXX X
    XXX XXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXX X
      XXXXXXXXXXXXXX XXXXX
      XXXXXXX
    X

    XXX X
      XXX XXX X XXX XXXXXXXXXXXX
      XXXXXXXXXXXXXXXX XX X XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    X XXXXXXXX X
      XXXXXXXXXXXXXX XXX
    X
  XXX

XXXXX
XXXXXXXXX
