XXXXXXXXX XXXXX
XXXXXX
XXXXXX
  XXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXX
  XXXXXX XXXXXXXXXXXXXXXX
    XXXXX X
      XXXXXXX XXXXX
      XXXXXXX XXXXX XXXX XX
      XXXXXXXXX XXXXXXXXX
      XXXXXX XXXXXX
    X

    XXXXX X
      XXXXXXXXXXXXXXXXX XXXXXXXX
      XXXXXXXXXXXXXX XXXXX
      XXXXXXX XX
      XXXXXXXX XXXXXX
      XXXXXXX XXXXX
      XXXXX XX
      XXXXXXXXX XXXXXXXXX
      XXXXXX XXXXX
    X
  XXXXXXXX
  XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX
XXXXXX
  XXXX XXXXXXXXXXXXX
    XXXXX XXXXXXXXXXX XXXXXXXXXXXXXXXX
  XXXXXX
XXXXXXX
XXXXXXX